### PR TITLE
Add `sep` to `cardinal` for converting decimals to ratios/proportions

### PR DESCRIPTION
**Pull request by elipousson**
Following up on #5 - this pull request includes updates to the examples, README, and pkgdown website.

### CODE REVIEW

**Comment by rossellhayes** [comment]
This is an excellent and much appreciated PR! Looking at it, I wonder if it might be better to add a new function `nom_ratio()` that covers the case where `sep` is specified. 

Right now we have great output for values where 0 is less than x is less than 1, but slightly awkward output for values where the absolute value of x is greater than or equal to 1:

``` r
nombre::cardinal(c(2/3, 3, 5/4), sep = "in")
#> [1] "two in three"        "three"               "one and one in four"
```
<sup>Created on 2021-10-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

With `nom_ratio()`, we could have:

``` r
nombre::ratio(c(2/3, 3, 5/4), sep = "in")
#> [1] "two in three" "three in one" "five in four"
```

What do you think?

**Comment by elipousson** [comment]
Great catch. Thanks for adding me as a contributor as well! I spent some time working on this last night and I think I've got it almost ready. I just need to finish setting up the tests and figure out how to handle it when `x` is 0.

One idea: I think it may be helpful to add `common_denom` as a named parameter that always is passed to `fracture::fracture()`. If `common_denom` is TRUE, 0 would be use the same common denominator as the other converted ratios, e.g. nom_ratio(c(0, 0.5, 1.5), sep = "in" common_denom = TRUE) should return "zero in four", "one in four", "three in four". If `common_denom` is FALSE (default), the second component of the ratio for 0 should default to 1, e.g. nom_ratio(c(0, 0.5), sep = "in") should return "zero in one" and "one in two". Does that make sense?

**Comment by rossellhayes** [comment]
I think that's a great approach to handling 0. I think that may be good default behavior for `fracture`, so I'll do some work there to get that working here!

**Comment by rossellhayes** [comment]
@elipousson I made a couple changes to `ratio()` that I think will help it fit in better with the package, but I'd like to hear your thoughts on everything before I merge.

- I removed special handling of `ratio(0)`. That case is now handled by rossellhayes/fracture#6
- I changed the default argument of `sep` to "in". I like the sound of "to" best, but I think it can be misleading in cases where 0 < `x` < 1, because "to" is often used to represent odds.
- I removed the requirement that `sep` come from a certain list. I think the list you provided had the best options for ratios, but I wouldn't want to limit anyone who has different ideas.

Other changes were just refactoring. This helped me find some bugs in the existing `nombre` functions!

**Comment by elipousson** [comment]
That all sounds good to me! Glad to contribute to the package. As a novice developer, it is definitely educational for me to explore how you've set up all the tests, examples, and default parameters for nombre.

**Comment by rossellhayes** [comment]
I'm not much more than a novice either (and a native Marylander too!) so I really appreciate your contribution. It's great to see someone using these skills to contribute to Baltimore!

**Pull request merged**
